//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 05:28:18 PM EST 
//


package cloud.data.integration.module.invoice.report.jaxb.parentreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PARENTID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="G_1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="REQUEST_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentid",
    "g1"
})
@XmlRootElement(name = "DATA_DS")
public class DATADS {

    @XmlElement(name = "PARENTID")
    protected int parentid;
    @XmlElement(name = "G_1", required = true)
    protected DATADS.G1 g1;

    /**
     * Gets the value of the parentid property.
     * 
     */
    public int getPARENTID() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     */
    public void setPARENTID(int value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the g1 property.
     * 
     * @return
     *     possible object is
     *     {@link DATADS.G1 }
     *     
     */
    public DATADS.G1 getG1() {
        return g1;
    }

    /**
     * Sets the value of the g1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATADS.G1 }
     *     
     */
    public void setG1(DATADS.G1 value) {
        this.g1 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="REQUEST_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestid"
    })
    public static class G1 {

        @XmlElement(name = "REQUEST_ID")
        protected int requestid;

        /**
         * Gets the value of the requestid property.
         * 
         */
        public int getREQUESTID() {
            return requestid;
        }

        /**
         * Sets the value of the requestid property.
         * 
         */
        public void setREQUESTID(int value) {
            this.requestid = value;
        }

    }

}
