//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.06 at 06:14:41 PM EST 
//


package cloud.data.integration.module.invoice.report.jaxb.partyname;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PARTY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="G_1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SUPPLIER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SUPPLIER_NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SUPPLIER_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SUPPLIER_SITE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PRIMARY_PAY_SITE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyname",
    "g1"
})
@XmlRootElement(name = "DATA_DS")
public class DATADS {

    @XmlElement(name = "PARTY_NAME", required = true)
    protected String partyname;
    @XmlElement(name = "G_1", required = true)
    protected DATADS.G1 g1;

    /**
     * Gets the value of the partyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTYNAME() {
        return partyname;
    }

    /**
     * Sets the value of the partyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTYNAME(String value) {
        this.partyname = value;
    }

    /**
     * Gets the value of the g1 property.
     * 
     * @return
     *     possible object is
     *     {@link DATADS.G1 }
     *     
     */
    public DATADS.G1 getG1() {
        return g1;
    }

    /**
     * Sets the value of the g1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATADS.G1 }
     *     
     */
    public void setG1(DATADS.G1 value) {
        this.g1 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SUPPLIER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SUPPLIER_NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SUPPLIER_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SUPPLIER_SITE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PRIMARY_PAY_SITE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "suppliername",
        "suppliernumber",
        "supplierid",
        "suppliersite",
        "primarypaysiteflag"
    })
    public static class G1 {

        @XmlElement(name = "SUPPLIER_NAME", required = true)
        protected String suppliername;
        @XmlElement(name = "SUPPLIER_NUMBER")
        protected int suppliernumber;
        @XmlElement(name = "SUPPLIER_ID")
        protected int supplierid;
        @XmlElement(name = "SUPPLIER_SITE", required = true)
        protected String suppliersite;
        @XmlElement(name = "PRIMARY_PAY_SITE_FLAG", required = true)
        protected String primarypaysiteflag;

        /**
         * Gets the value of the suppliername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSUPPLIERNAME() {
            return suppliername;
        }

        /**
         * Sets the value of the suppliername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSUPPLIERNAME(String value) {
            this.suppliername = value;
        }

        /**
         * Gets the value of the suppliernumber property.
         * 
         */
        public int getSUPPLIERNUMBER() {
            return suppliernumber;
        }

        /**
         * Sets the value of the suppliernumber property.
         * 
         */
        public void setSUPPLIERNUMBER(int value) {
            this.suppliernumber = value;
        }

        /**
         * Gets the value of the supplierid property.
         * 
         */
        public int getSUPPLIERID() {
            return supplierid;
        }

        /**
         * Sets the value of the supplierid property.
         * 
         */
        public void setSUPPLIERID(int value) {
            this.supplierid = value;
        }

        /**
         * Gets the value of the suppliersite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSUPPLIERSITE() {
            return suppliersite;
        }

        /**
         * Sets the value of the suppliersite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSUPPLIERSITE(String value) {
            this.suppliersite = value;
        }

        /**
         * Gets the value of the primarypaysiteflag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRIMARYPAYSITEFLAG() {
            return primarypaysiteflag;
        }

        /**
         * Sets the value of the primarypaysiteflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRIMARYPAYSITEFLAG(String value) {
            this.primarypaysiteflag = value;
        }

    }

}
