
package cloud.data.integration.common.erpintegrationservice.webservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ErpIntegrationService", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ErpIntegrationService {


    /**
     * 
     * @param requestId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getESSJobStatus")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getESSJobStatus", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetESSJobStatus")
    @ResponseWrapper(localName = "getESSJobStatusResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetESSJobStatusResponse")
    public String getESSJobStatus(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        long requestId)
        throws ServiceException
    ;

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns cloud.data.integration.common.erpintegrationservice.webservice.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cloud.data.integration.common.erpintegrationservice.webservice.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param requestId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getESSJobStatusAsync")
    @Oneway
    @RequestWrapper(localName = "getESSJobStatusAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetESSJobStatusAsync")
    public void getESSJobStatusAsync(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        long requestId);

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param paramList
     * @param jobDefinitionName
     * @param jobPackageName
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/submitESSJobRequest")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "submitESSJobRequest", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitESSJobRequest")
    @ResponseWrapper(localName = "submitESSJobRequestResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitESSJobRequestResponse")
    public long submitESSJobRequest(
        @WebParam(name = "jobPackageName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobPackageName,
        @WebParam(name = "jobDefinitionName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobDefinitionName,
        @WebParam(name = "paramList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> paramList)
        throws ServiceException
    ;

    /**
     * 
     * @param paramList
     * @param jobDefinitionName
     * @param jobPackageName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/submitESSJobRequestAsync")
    @Oneway
    @RequestWrapper(localName = "submitESSJobRequestAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitESSJobRequestAsync")
    public void submitESSJobRequestAsync(
        @WebParam(name = "jobPackageName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobPackageName,
        @WebParam(name = "jobDefinitionName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobDefinitionName,
        @WebParam(name = "paramList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> paramList);

    /**
     * 
     * @param paramList
     * @param callbackURL
     * @param jobDefinitionName
     * @param jobPackageName
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/submitJobWithOutput")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "submitJobWithOutput", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitJobWithOutput")
    @ResponseWrapper(localName = "submitJobWithOutputResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitJobWithOutputResponse")
    public long submitJobWithOutput(
        @WebParam(name = "jobPackageName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobPackageName,
        @WebParam(name = "jobDefinitionName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobDefinitionName,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "paramList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> paramList)
        throws ServiceException
    ;

    /**
     * 
     * @param paramList
     * @param callbackURL
     * @param jobDefinitionName
     * @param jobPackageName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/submitJobWithOutputAsync")
    @Oneway
    @RequestWrapper(localName = "submitJobWithOutputAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.SubmitJobWithOutputAsync")
    public void submitJobWithOutputAsync(
        @WebParam(name = "jobPackageName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobPackageName,
        @WebParam(name = "jobDefinitionName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobDefinitionName,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "paramList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> paramList);

    /**
     * 
     * @param comments
     * @param prefix
     * @param account
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentIdsForFilePrefix")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getDocumentIdsForFilePrefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentIdsForFilePrefix")
    @ResponseWrapper(localName = "getDocumentIdsForFilePrefixResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentIdsForFilePrefixResponse")
    public List<String> getDocumentIdsForFilePrefix(
        @WebParam(name = "prefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String prefix,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String account,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments)
        throws ServiceException
    ;

    /**
     * 
     * @param comments
     * @param prefix
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentIdsForFilePrefixAsync")
    @Oneway
    @RequestWrapper(localName = "getDocumentIdsForFilePrefixAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentIdsForFilePrefixAsync")
    public void getDocumentIdsForFilePrefixAsync(
        @WebParam(name = "prefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String prefix,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String account,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments);

    /**
     * 
     * @param documentId
     * @return
     *     returns cloud.data.integration.common.erpintegrationservice.webservice.DocumentDetails
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentForDocumentId")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getDocumentForDocumentId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentForDocumentId")
    @ResponseWrapper(localName = "getDocumentForDocumentIdResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentForDocumentIdResponse")
    public DocumentDetails getDocumentForDocumentId(
        @WebParam(name = "DocumentId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String documentId)
        throws ServiceException
    ;

    /**
     * 
     * @param documentId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentForDocumentIdAsync")
    @Oneway
    @RequestWrapper(localName = "getDocumentForDocumentIdAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentForDocumentIdAsync")
    public void getDocumentForDocumentIdAsync(
        @WebParam(name = "DocumentId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String documentId);

    /**
     * 
     * @param comments
     * @param prefix
     * @param account
     * @return
     *     returns java.util.List<cloud.data.integration.common.erpintegrationservice.webservice.DocumentDetails>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentsForFilePrefix")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "getDocumentsForFilePrefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentsForFilePrefix")
    @ResponseWrapper(localName = "getDocumentsForFilePrefixResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentsForFilePrefixResponse")
    public List<DocumentDetails> getDocumentsForFilePrefix(
        @WebParam(name = "prefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String prefix,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String account,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments)
        throws ServiceException
    ;

    /**
     * 
     * @param comments
     * @param prefix
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/getDocumentsForFilePrefixAsync")
    @Oneway
    @RequestWrapper(localName = "getDocumentsForFilePrefixAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.GetDocumentsForFilePrefixAsync")
    public void getDocumentsForFilePrefixAsync(
        @WebParam(name = "prefix", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String prefix,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String account,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments);

    /**
     * 
     * @param document
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/uploadFileToUcm")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "uploadFileToUcm", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.UploadFileToUcm")
    @ResponseWrapper(localName = "uploadFileToUcmResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.UploadFileToUcmResponse")
    public String uploadFileToUcm(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetails document)
        throws ServiceException
    ;

    /**
     * 
     * @param document
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/uploadFileToUcmAsync")
    @Oneway
    @RequestWrapper(localName = "uploadFileToUcmAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.UploadFileToUcmAsync")
    public void uploadFileToUcmAsync(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetails document);

    /**
     * 
     * @param requestId
     * @param fileType
     * @return
     *     returns java.util.List<cloud.data.integration.common.erpintegrationservice.webservice.DocumentDetails>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadESSJobExecutionDetails")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "downloadESSJobExecutionDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadESSJobExecutionDetails")
    @ResponseWrapper(localName = "downloadESSJobExecutionDetailsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadESSJobExecutionDetailsResponse")
    public List<DocumentDetails> downloadESSJobExecutionDetails(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestId,
        @WebParam(name = "fileType", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String fileType)
        throws ServiceException
    ;

    /**
     * 
     * @param comments
     * @param documentId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/appendFileComment")
    @RequestWrapper(localName = "appendFileComment", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.AppendFileComment")
    @ResponseWrapper(localName = "appendFileCommentResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.AppendFileCommentResponse")
    public void appendFileComment(
        @WebParam(name = "documentId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String documentId,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments)
        throws ServiceException
    ;

    /**
     * 
     * @param comments
     * @param documentId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/appendFileCommentAsync")
    @Oneway
    @RequestWrapper(localName = "appendFileCommentAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.AppendFileCommentAsync")
    public void appendFileCommentAsync(
        @WebParam(name = "documentId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String documentId,
        @WebParam(name = "comments", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String comments);

    /**
     * 
     * @param requestId
     * @param fileType
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadESSJobExecutionDetailsAsync")
    @Oneway
    @RequestWrapper(localName = "downloadESSJobExecutionDetailsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadESSJobExecutionDetailsAsync")
    public void downloadESSJobExecutionDetailsAsync(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestId,
        @WebParam(name = "fileType", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String fileType);

    /**
     * 
     * @param requestId
     * @return
     *     returns java.util.List<cloud.data.integration.common.erpintegrationservice.webservice.DocumentDetails>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadExportOutput")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "downloadExportOutput", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadExportOutput")
    @ResponseWrapper(localName = "downloadExportOutputResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadExportOutputResponse")
    public List<DocumentDetails> downloadExportOutput(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestId)
        throws ServiceException
    ;

    /**
     * 
     * @param requestId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadExportOutputAsync")
    @Oneway
    @RequestWrapper(localName = "downloadExportOutputAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.DownloadExportOutputAsync")
    public void downloadExportOutputAsync(
        @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestId);

    /**
     * 
     * @param interfaceDetails
     * @param document
     * @param callbackURL
     * @param jobList
     * @param notificationCode
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/loadAndImportData")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "loadAndImportData", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.LoadAndImportData")
    @ResponseWrapper(localName = "loadAndImportDataResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.LoadAndImportDataResponse")
    public long loadAndImportData(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetails document,
        @WebParam(name = "jobList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<EssJob> jobList,
        @WebParam(name = "interfaceDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String interfaceDetails,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceDetails
     * @param document
     * @param callbackURL
     * @param jobList
     * @param notificationCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/loadAndImportDataAsync")
    @Oneway
    @RequestWrapper(localName = "loadAndImportDataAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.LoadAndImportDataAsync")
    public void loadAndImportDataAsync(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetails document,
        @WebParam(name = "jobList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<EssJob> jobList,
        @WebParam(name = "interfaceDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String interfaceDetails,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL);

    /**
     * 
     * @param jobName
     * @param documentIDs
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/confirmExtractConsumption")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "confirmExtractConsumption", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ConfirmExtractConsumption")
    @ResponseWrapper(localName = "confirmExtractConsumptionResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ConfirmExtractConsumptionResponse")
    public String confirmExtractConsumption(
        @WebParam(name = "jobName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobName,
        @WebParam(name = "documentIDs", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> documentIDs)
        throws ServiceException
    ;

    /**
     * 
     * @param jobName
     * @param documentIDs
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/confirmExtractConsumptionAsync")
    @Oneway
    @RequestWrapper(localName = "confirmExtractConsumptionAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ConfirmExtractConsumptionAsync")
    public void confirmExtractConsumptionAsync(
        @WebParam(name = "jobName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobName,
        @WebParam(name = "documentIDs", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<String> documentIDs);

    /**
     * 
     * @param jobOptions
     * @param document
     * @param callbackURL
     * @param jobDetails
     * @param notificationCode
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/importBulkData")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "importBulkData", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ImportBulkData")
    @ResponseWrapper(localName = "importBulkDataResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ImportBulkDataResponse")
    public long importBulkData(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetail document,
        @WebParam(name = "jobDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<EssJob> jobDetails,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions)
        throws ServiceException
    ;

    /**
     * 
     * @param jobOptions
     * @param document
     * @param callbackURL
     * @param jobDetails
     * @param notificationCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/importBulkDataAsync")
    @Oneway
    @RequestWrapper(localName = "importBulkDataAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ImportBulkDataAsync")
    public void importBulkDataAsync(
        @WebParam(name = "document", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DocumentDetail document,
        @WebParam(name = "jobDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<EssJob> jobDetails,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions);

    /**
     * 
     * @param jobOptions
     * @param callbackURL
     * @param requestIds
     * @param notificationCode
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/extractAndPurge")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "extractAndPurge", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExtractAndPurge")
    @ResponseWrapper(localName = "extractAndPurgeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExtractAndPurgeResponse")
    public long extractAndPurge(
        @WebParam(name = "requestIds", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestIds,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions)
        throws ServiceException
    ;

    /**
     * 
     * @param jobOptions
     * @param callbackURL
     * @param requestIds
     * @param notificationCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/extractAndPurgeAsync")
    @Oneway
    @RequestWrapper(localName = "extractAndPurgeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExtractAndPurgeAsync")
    public void extractAndPurgeAsync(
        @WebParam(name = "requestIds", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String requestIds,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions);

    /**
     * 
     * @param jobName
     * @param jobOptions
     * @param parameterList
     * @param callbackURL
     * @param notificationCode
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/exportBulkData")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "exportBulkData", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExportBulkData")
    @ResponseWrapper(localName = "exportBulkDataResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExportBulkDataResponse")
    public long exportBulkData(
        @WebParam(name = "jobName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobName,
        @WebParam(name = "parameterList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String parameterList,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode)
        throws ServiceException
    ;

    /**
     * 
     * @param jobName
     * @param jobOptions
     * @param parameterList
     * @param callbackURL
     * @param notificationCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/exportBulkDataAsync")
    @Oneway
    @RequestWrapper(localName = "exportBulkDataAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.erpintegrationservice.webservice.ExportBulkDataAsync")
    public void exportBulkDataAsync(
        @WebParam(name = "jobName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobName,
        @WebParam(name = "parameterList", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String parameterList,
        @WebParam(name = "jobOptions", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String jobOptions,
        @WebParam(name = "callbackURL", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String callbackURL,
        @WebParam(name = "notificationCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String notificationCode);

}
