
package cloud.data.integration.common.erpintegrationservice.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import cloud.data.integration.module.invoice.util.InvoiceUtil;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ErpIntegrationService", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/", wsdlLocation = "https://efff-test.fin.us6.oraclecloud.com/publicFinancialCommonErpIntegration/ErpIntegrationService?WSDL")
public class ErpIntegrationService_Service
    extends Service
{

    private final static URL ERPINTEGRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERPINTEGRATIONSERVICE_EXCEPTION;
    private final static QName ERPINTEGRATIONSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/", "ErpIntegrationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(InvoiceUtil.getPropertyValue("ERP_INTEGRATION_SERVICE_URL_WSDL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPINTEGRATIONSERVICE_WSDL_LOCATION = url;
        ERPINTEGRATIONSERVICE_EXCEPTION = e;
    }

    public ErpIntegrationService_Service() {
        super(__getWsdlLocation(), ERPINTEGRATIONSERVICE_QNAME);
    }

    public ErpIntegrationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPINTEGRATIONSERVICE_QNAME, features);
    }

    public ErpIntegrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, ERPINTEGRATIONSERVICE_QNAME);
    }

    public ErpIntegrationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPINTEGRATIONSERVICE_QNAME, features);
    }

    public ErpIntegrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpIntegrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ErpIntegrationService
     */
    @WebEndpoint(name = "ErpIntegrationServiceSoapHttpPort")
    public ErpIntegrationService getErpIntegrationServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/", "ErpIntegrationServiceSoapHttpPort"), ErpIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErpIntegrationService
     */
    @WebEndpoint(name = "ErpIntegrationServiceSoapHttpPort")
    public ErpIntegrationService getErpIntegrationServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/", "ErpIntegrationServiceSoapHttpPort"), ErpIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPINTEGRATIONSERVICE_EXCEPTION!= null) {
            throw ERPINTEGRATIONSERVICE_EXCEPTION;
        }
        return ERPINTEGRATIONSERVICE_WSDL_LOCATION;
    }

}
