//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.17 at 03:10:56 PM EST 
//


package cloud.data.integration.module.invoice.report.jaxb.coa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_INPUT_COA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="G_1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LOOKUP_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="INPUT_COA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SCC_COA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DISTRIBUTION_SET_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pinputcoa",
    "g1"
})
@XmlRootElement(name = "DATA_DS")
public class DATADS {

    @XmlElement(name = "P_INPUT_COA", required = true)
    protected String pinputcoa;
    @XmlElement(name = "G_1", required = true)
    protected DATADS.G1 g1;

    /**
     * Gets the value of the pinputcoa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINPUTCOA() {
        return pinputcoa;
    }

    /**
     * Sets the value of the pinputcoa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINPUTCOA(String value) {
        this.pinputcoa = value;
    }

    /**
     * Gets the value of the g1 property.
     * 
     * @return
     *     possible object is
     *     {@link DATADS.G1 }
     *     
     */
    public DATADS.G1 getG1() {
        return g1;
    }

    /**
     * Sets the value of the g1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATADS.G1 }
     *     
     */
    public void setG1(DATADS.G1 value) {
        this.g1 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LOOKUP_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="INPUT_COA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SCC_COA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DISTRIBUTION_SET_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lookuptype",
        "inputcoa",
        "sequence",
        "scccoa",
        "distributionsetname"
    })
    public static class G1 {

        @XmlElement(name = "LOOKUP_TYPE", required = true)
        protected String lookuptype;
        @XmlElement(name = "INPUT_COA", required = true)
        protected String inputcoa;
        @XmlElement(name = "SEQUENCE")
        protected int sequence;
        @XmlElement(name = "SCC_COA", required = true)
        protected String scccoa;
        @XmlElement(name = "DISTRIBUTION_SET_NAME", required = true)
        protected String distributionsetname;

        /**
         * Gets the value of the lookuptype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLOOKUPTYPE() {
            return lookuptype;
        }

        /**
         * Sets the value of the lookuptype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLOOKUPTYPE(String value) {
            this.lookuptype = value;
        }

        /**
         * Gets the value of the inputcoa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINPUTCOA() {
            return inputcoa;
        }

        /**
         * Sets the value of the inputcoa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINPUTCOA(String value) {
            this.inputcoa = value;
        }

        /**
         * Gets the value of the sequence property.
         * 
         */
        public int getSEQUENCE() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         */
        public void setSEQUENCE(int value) {
            this.sequence = value;
        }

        /**
         * Gets the value of the scccoa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSCCCOA() {
            return scccoa;
        }

        /**
         * Sets the value of the scccoa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSCCCOA(String value) {
            this.scccoa = value;
        }

        /**
         * Gets the value of the distributionsetname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDISTRIBUTIONSETNAME() {
            return distributionsetname;
        }

        /**
         * Sets the value of the distributionsetname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDISTRIBUTIONSETNAME(String value) {
            this.distributionsetname = value;
        }

    }

}
